#pragma once

///////////////////////////////////////////////////
// AUTOGENERATED: 
// DO NOT EDIT THIS FILE
// EDIT: roselib/internal/generate_bindings.py
// Generated: 2022-05-28 00:23:02
///////////////////////////////////////////////////
#include <roselib/context.h>

typedef float (*rose_utils_add_ft)(float a, float b);
ROSE_EXPORT rose_utils_add_ft c_rose_utils_add;


#ifdef __cplusplus
namespace rose {
namespace utils {
  inline float add(float a, float b) {
    return c_rose_utils_add(a, b);
  }
}
}
#endif

#ifdef ROSE_ENGINE_INTERNAL
float g_rose_utils_add(float a, float b);
#endif

#if defined(ROSE_ENGINE_INTERNAL) && defined(ROSE_INJECT_BINDINGS) 
//TODO: create unix binding.
inline void inject_bindings(HMODULE handle) { 
  {
    auto fun = (rose_utils_add_ft*)(GetProcAddress(handle, "c_rose_utils_add"));
    if(GetLastError() == 0) {
      *fun = g_rose_utils_add;
    } else {
      fprintf(stderr, "Warning: Couldn't find function %s \n", "c_rose_utils_add");
    }
  }
}
#endif

#if defined(ROSE_BINDINGS_IMPL) 
static rose_utils_add_ft c_rose_utils_add = 0;
#endif 
