///////////////////////////////////////////////////////////////////
// AUTOGENERATED do not edit by hand                             //
///////////////////////////////////////////////////////////////////

#pragma once


#include <components/computils.h>

#include <components/matrix4.h>
#include <components/camera.h>
#include <components/objectid.h>
#include <components/vector3.h>
#include <components/collider.h>
#include <components/cubehero.h>
#include <components/cubeworld.h>
#include <components/vector2.h>
#include <components/soundassetref.h>
#include <components/quaternion.h>
#include <components/transform.h>
#include <components/hero.h>
#include <components/kraxler.h>
#include <components/kraxlersystemstate.h>
#include <components/meshassetref.h>
#include <components/microsystem.h>
#include <components/shaderassetref.h>
#include <components/raytracer.h>
#include <components/roseoptions.h>
#include <components/textureassetref.h>
#include <components/sceneobject.h>
#include <components/wheelchairsystemstate.h>
#include <components/scene.h>
