///////////////////////////////////////////////////////////////////
// AUTOGENERATED do not edit by hand                             //
///////////////////////////////////////////////////////////////////
#pragma once
#include <components/computils.h>
#include <serializer/serializer.h>
#include <rose/ecs.h>
#include <cstring>

#include <components/vector3.h>
namespace rose {
namespace ecs {
struct Cubechan {
  vector3 position;

  bool equals(const Cubechan & rhs) const {
    return
      position == rhs.position;
  }
};

inline void construct_defaults(Cubechan & o) {
  std::memset(&o, 0, sizeof(Cubechan));
  construct_defaults(o.position);
}

inline bool operator==(const Cubechan &lhs, const Cubechan &rhs) {
  return lhs.equals(rhs);
}

inline bool operator!=(const Cubechan &lhs, const Cubechan &rhs) {
  return !lhs.equals(rhs);
}

///////////////////////////////////////////////////////////////////
// serializer                                                    //
///////////////////////////////////////////////////////////////////
inline void serialize(Cubechan &o, ISerializer &s) {
  if(s.node_begin("Cubechan", rose::hash("Cubechan"), &o)) {
    s.key("position");
    serialize(o.position, s);
    s.node_end();
  }
  s.end();
}

///////////////////////////////////////////////////////////////////
// deserializer                                                  //
///////////////////////////////////////////////////////////////////
inline void deserialize(Cubechan &o, IDeserializer &s) {
  construct_defaults(o);

  while (s.next_key()) {
    switch (s.hash_key()) {
      case rose::hash("position"):
        deserialize(o.position, s);
        break;
      default: s.skip_key(); break;
    }
  }
}

///////////////////////////////////////////////////////////////////
// randomize                                                     //
///////////////////////////////////////////////////////////////////
inline void randomize(Cubechan &o, rose::hash_value & h) {
  randomize(o.position, h);
}
} //namespace ecs

///////////////////////////////////////////////////////////////////
// hashing                                                       //
///////////////////////////////////////////////////////////////////
  inline hash_value hash(ecs::Cubechan &o) {
    hash_value h = hash(o.position);
    return h;
  }
} //namespace rose
