///////////////////////////////////////////////////////////////////
// AUTOGENERATED do not edit by hand                             //
///////////////////////////////////////////////////////////////////
#pragma once
#include <components/computils.h>
#include <serializer/serializer.h>
#include <rose/ecs.h>
#include <cstring>

#include <components/matrix4.h>
#include <components/vector3.h>
#include <components/quaternion.h>
#include <components/vector3.h>
namespace rose {
namespace ecs {
struct Transform {
  matrix4 mvt;
  vector3 position;
  quaternion rotation;
  vector3 scale;

  bool equals(const Transform & rhs) const {
    return
      mvt == rhs.mvt &&
      position == rhs.position &&
      rotation == rhs.rotation &&
      scale == rhs.scale;
  }
};

inline void construct_defaults(Transform & o) {
  std::memset(&o, 0, sizeof(Transform));
  o.mvt = identity4();
  o.position = ::vector(0,0,0);
  o.rotation = qidentity();
  o.scale = ::vector(1,1,1);
}

inline bool operator==(const Transform &lhs, const Transform &rhs) {
  return lhs.equals(rhs);
}

inline bool operator!=(const Transform &lhs, const Transform &rhs) {
  return !lhs.equals(rhs);
}

///////////////////////////////////////////////////////////////////
// serializer                                                    //
///////////////////////////////////////////////////////////////////
inline void serialize(Transform &o, ISerializer &s) {
  if(s.node_begin("Transform", rose::hash("Transform"), &o)) {
    s.key("mvt");
    serialize(o.mvt, s);
    s.key("position");
    serialize(o.position, s);
    s.key("rotation");
    serialize(o.rotation, s);
    s.key("scale");
    serialize(o.scale, s);
    s.node_end();
  }
  s.end();
}

///////////////////////////////////////////////////////////////////
// deserializer                                                  //
///////////////////////////////////////////////////////////////////
inline void deserialize(Transform &o, IDeserializer &s) {
  construct_defaults(o);

  while (s.next_key()) {
    switch (s.hash_key()) {
      case rose::hash("mvt"):
        deserialize(o.mvt, s);
        break;
      case rose::hash("position"):
        deserialize(o.position, s);
        break;
      case rose::hash("rotation"):
        deserialize(o.rotation, s);
        break;
      case rose::hash("scale"):
        deserialize(o.scale, s);
        break;
      default: s.skip_key(); break;
    }
  }
}

///////////////////////////////////////////////////////////////////
// randomize                                                     //
///////////////////////////////////////////////////////////////////
inline void randomize(Transform &o, rose::hash_value & h) {
  randomize(o.mvt, h);
  randomize(o.position, h);
  randomize(o.rotation, h);
  randomize(o.scale, h);
}
} //namespace ecs

///////////////////////////////////////////////////////////////////
// hashing                                                       //
///////////////////////////////////////////////////////////////////
  inline hash_value hash(const ecs::Transform &o) {
    hash_value h = hash(o.mvt);
    h = xor64(h);
    h ^= hash(o.position);
    h = xor64(h);
    h ^= hash(o.rotation);
    h = xor64(h);
    h ^= hash(o.scale);
    return h;
  }
} //namespace rose
