#pragma once

////////////////////////////////////////
// AUTOGENERATED: 
// DO NOT EDIT THIS FILE
// EDIT: roselib/internal/generate_bindings.py
// Bindings hash: 15226
///////////////////////////////////////////////////
#include <roselib/context.h>
#include <rose/hash.h>
#include <cstdio>

#include <rose/internal/bindings.h>
//TODO: consider adding fake stubs for the functions that throw.
rose_internal_get_event_queue_ft c_rose_internal_get_event_queue = 0;
rose_filewatcher_watch_path_ft c_rose_filewatcher_watch_path = 0;
rose_filewatcher_unwatch_path_ft c_rose_filewatcher_unwatch_path = 0;
