#pragma once

///////////////////////////////////////////////////
// AUTOGENERATED: 
// DO NOT EDIT THIS FILE
// EDIT: roselib/internal/generate_bindings.py
// Bindings hash: 48287
///////////////////////////////////////////////////
#include <rose/hash.h>

#include <roselib/context.h>
#include <rose/internal/bindings_typedef.h>
ROSE_EXPORT rose_internal_create_or_fetch_worldstate_ft c_rose_internal_create_or_fetch_worldstate;
ROSE_EXPORT rose_internal_register_singleton_class_instance_ft c_rose_internal_register_singleton_class_instance;
ROSE_EXPORT rose_internal_unregister_singleton_class_instance_ft c_rose_internal_unregister_singleton_class_instance;
ROSE_EXPORT rose_internal_get_singleton_class_instance_ft c_rose_internal_get_singleton_class_instance;
ROSE_EXPORT rose_filewatcher_watch_path_ft c_rose_filewatcher_watch_path;
ROSE_EXPORT rose_filewatcher_unwatch_path_ft c_rose_filewatcher_unwatch_path;
ROSE_EXPORT int c_rose_subsystem_instance_id; 

#ifdef __cplusplus
namespace rose {
namespace filewatcher {
  inline int watch_path(const char * path) {
    return c_rose_filewatcher_watch_path(c_rose_subsystem_instance_id, path);
  }
}
namespace filewatcher {
  inline bool unwatch_path(int id) {
    return c_rose_filewatcher_unwatch_path(c_rose_subsystem_instance_id, id);
  }
}
}
#endif
