#pragma once

///////////////////////////////////////////////////
// AUTOGENERATED: 
// DO NOT EDIT THIS FILE
// EDIT: roselib/internal/generate_bindings.py
// Bindings hash: 24331
///////////////////////////////////////////////////
#include <rose/hash.h>
#include <rose/world.h>
#include <rose/eventqueue.h>
#include <rose/internal/singletonregister.h>

#include <rose/internal/bindings_typedef.h>
//TODO: consider adding fake stubs for the functions that throw.
rose_internal_get_event_queue_ft c_rose_internal_get_event_queue = 0;
rose_internal_create_or_fetch_worldstate_ft c_rose_internal_create_or_fetch_worldstate = 0;
rose_filewatcher_watch_path_ft c_rose_filewatcher_watch_path = 0;
rose_filewatcher_unwatch_path_ft c_rose_filewatcher_unwatch_path = 0;
