name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: checkout roselib
      uses: actions/checkout@v3
      with:
        repository: RicoP/roselib
        path: ./roselib

    - name: checkout Catch2
      uses: actions/checkout@v3
      with:
        repository: catchorg/Catch2
        path: ./Catch2
        branch: v2.x

    - name: Setup premake
      uses: abel0b/setup-premake@v2.1
      with:
        version: "5.0.0-beta2"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: create solution
      working-directory: roselib
      run: premake5 vs2019

    - name: Build solution
      working-directory: roselib
      run: msbuild ./.build/projects/roselib.sln

    - name: execute test
      working-directory: roselib/test
      run: .\.build\bin\Debug\tests.exe
